apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        shgattu/jx3-kubernetes: true
        shgattu/spring: true
        shgattu/spring-boot-gradle-mvc: true
        shgattu/spring-demo: true
        shgattu/spring-test: true
        shgattu/springapp: true
        shgattu/springapporiginal: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        shgattu/jx3-kubernetes: merge
        shgattu/spring: merge
        shgattu/spring-boot-gradle-mvc: merge
        shgattu/spring-demo: merge
        shgattu/spring-test: merge
        shgattu/springapp: merge
        shgattu/springapporiginal: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - shgattu/jx3-kubernetes
        - shgattu/spring-boot-gradle-mvc
        - shgattu/spring-demo
        - shgattu/spring-test
        - shgattu/spring
        - shgattu/springapp
        - shgattu/springapporiginal
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - shgattu/jx3-kubernetes
        - shgattu/spring-boot-gradle-mvc
        - shgattu/spring-demo
        - shgattu/spring-test
        - shgattu/spring
        - shgattu/springapp
        - shgattu/springapporiginal
      target_url: http://lighthouse-jx./merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
