filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-production
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
releases:
- chart: dev/spring
  version: 0.0.1
  name: spring
  values:
  - jx-values.yaml
- chart: dev/spring-test
  version: 0.0.1
  name: spring-test
templates: {}
renderedvalues: {}
